# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Piston
tagline:          A user friendly game engine written in Rust
url:              https://piston.rs
paginate:         1
baseurl:          /
author:
    name:         PistonDevelopers
    url:          https://piston.rs
    email:        contact@piston.rs

# Custom vars
version:          1.0.0
github:
    repo:         https://github.com/PistonDevelopers/pistondevelopers.github.io

# Files excluded from site build
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - README.md
    - Rakefile
